---
name: Python Tests

on:
  pull_request:
    branches: [master, nightly]
    types: [opened, synchronize, reopened]

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, ubuntu-18.04, macos-10.15]
        architecture: [x64]
        include:  # additional runs
          - os: windows-2019
            architecture: x86

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3  # https://github.com/actions/setup-python
        with:
          python-version: '3.9'
          architecture: ${{ matrix.architecture }}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install -r requirements-dev.txt

      - name: Compile Locale Translations
        run: |
          python ./scripts/_locale.py --compile

      - name: Compile Docs
        run: |
          cd docs
          make html

      - name: Test with pytest
        run: |
          python -m pytest -v
